### ISSUE TITLE
自从用了这个，废了，切换源也连不上

### ISSUE THREAD

**Issue by xlw686** [matpool/matools#5]
自从用了这个，废了
UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: anaconda
  channel url: https://anaconda.mirrors.sjtug.sjtu.edu.cn/anaconda
  error code: 403

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.

**Comment by 0of** [comment]
移除 ~/.condarc 试试

**Comment by TDisWatchingU** [comment]
sorry for that
`sjtug` pypi/conda mirror already removed from the script now.
- `https://anaconda.mirrors.sjtug.sjtu.edu.cn/anaconda`
- `https://mirror.sjtu.edu.cn/pypi/web/simple/`

please `git pull` and switch ur conda mirror with latest script.
